# Generated by Django 4.1.5 on 2023-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False, verbose_name='engine_id')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('horse_power', models.PositiveSmallIntegerField(verbose_name='horse power')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
            ],
        ),
    ]
